server:
  port: 8080
  servlet:
    context-path: /flavour-compass
api:
  restApiToConsume:
    url:

logging:
  level:
    org.springframework.security: INFO
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/LSProject
    username: postgres
    password: terroR997
    hikari:
      idle-timeout: 10000
      connectionTimeout: 20000
      minimumIdle: 10
      maximumPoolSize: 20
  jpa:
    hibernate:
      format_sql: true
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  flyway:
    baseline-on-migrate: true
  security:
    enabled: true
